### PR TITLE
Improved

### PR DESCRIPTION
**Pull request by thing-a-verse**
Improved colours, Mercator projection, some adjustment of messaging

### CODE REVIEW

**Comment by thing-a-verse** [comment]
Nope. Wrong repo. Please ignore

**Comment by thing-a-verse** [comment]
Pull in error

**Comment by hrbrmstr** [comment]
I'll look in a bit. If Mercator is not an optional projection (like a toggle) I can't accept the PR.

**Comment by hrbrmstr** [comment]
oh ignore. got it.

**Pull request closed without merging**
